//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAH.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MAH.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _330_160_65_26 {
            get {
                object obj = ResourceManager.GetObject("_330_160_65_26", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 4,支援型莉奥妮丝,1,5
        ///9,支援型依缇尔,1,3
        ///15,第二型兰玛洛克,1,4
        ///16,试作型伏提庚,1,10
        ///18,第二型玛洛斯,1,5
        ///40,制御型贝德维尔,1,3
        ///41,特殊型尤文之狮,1,5
        ///46,第二型亚格拉文,1,6
        ///47,第二型卡尔迪斯,1,6
        ///51,第二型凯尔丹,1,6
        ///52,第二型卡洛格雷南,1,11
        ///54,第二型马伯纳格林,1,9
        ///65,特殊型格林格莱特,1,3
        ///66,教练型凯,1,5
        ///68,第二型伯纳德,1,4
        ///73,第二型艾恩赛德,1,7
        ///78,支援型奥尔特莉特,1,4
        ///79,第二型提尔拉蒙,1,6
        ///83,支援型贝莉珊,1,3
        ///85,第二型布鲁诺,1,4
        ///87,支援型艾尔莎,1,7
        ///89,第二型梅利甘斯,1,4
        ///100,支援型布兰奇芙蓉,1,9
        ///105,第二型卡多,1,6
        ///108,第二型佩里诺亚,1,3
        ///119,玛纳南,1,10
        ///126,第二型柏德玛戈斯,1,6
        ///132,第二型小波尔斯,1,3
        ///139,第二型海琳,1,3
        ///140,特殊型安波罗修,1,11
        ///141,支援型奥尔温,1,5
        ///390,切尔莉,1,99
        ///8,支援型 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string cn {
            get {
                return ResourceManager.GetString("cn", resourceCulture);
            }
        }
    }
}
